#!/bin/bash

set -e

VERSION=0.9998

DIR=$1
if [ -z "$DIR" ]; then
    echo Usage: $0 [DIRECTORY]
    exit 1
fi

# For main Sqitch build, the main tag is "latest" and there
# is no sub-package.
PKG=""
TAG="latest"
if [ "$DIR" != "." ]; then
    # For oher builds, we need to append a sub-package name and use the
    # diretory name as the main tag.
    cd $DIR
    PKG="-$DIR"
    TAG="$DIR"
fi

docker build --pull \
  --label org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label org.opencontainers.image.authors='Sqitch Hackers <sqitch-hackers@googlegroups.com>' \
  --label org.opencontainers.image.url="https://hub.docker.com/r/sqitch/sqitch/" \
  --label org.opencontainers.image.documentation="https://github.com/sqitchers/docker-sqitch#readme" \
  --label org.opencontainers.image.source="https://github.com/sqitchers/docker-sqitch" \
  --label org.opencontainers.image.version="0.9998" \
  --label org.opencontainers.image.revision="$(git rev-parse --abbrev-ref HEAD)" \
  --label org.opencontainers.image.vendor="The Sqitch Community" \
  --label org.opencontainers.image.licenses="MIT" \
  --label org.opencontainers.image.ref.name="sqitch${PKG}-${VERSION}" \
  --label org.opencontainers.image.title="Sqitch" \
  --label org.opencontainers.image.description="Sane database change management" \
  --tag sqitch/sqitch:${TAG} \
  --tag sqitch/sqitch:${VERSION}${PKG} \
  --build-arg VERSION=${VERSION} \
  .

