#!/bin/bash

set -e

NAME=sqitch
VERSION=1.2.1

DIR=${DIR:=.}
REGISTRY=${REGISTRY:="$NAME"}

# For main Sqitch build, the main tag is "latest" and there
# is no sub-package.
PKG=""
TAG="latest"
if [ "$DIR" != "." ]; then
    # For other builds, we need to append a sub-package name and use the
    # diretory name as the main tag.
    cd $DIR
    PKG="-$DIR"
    TAG="$DIR"
fi

# Always include "latest" and the version.
tagopt=(
    --tag "${REGISTRY}/${NAME}:${TAG}"
    --tag "${REGISTRY}/${NAME}:${VERSION}${PKG}"
)

# Include the git tag if differnt from the version.
if [ "$GITHUB_REF_TYPE" == "tag" ]; then
    GIT_TAG=${GITHUB_REF/refs\/tags\//}
    if [ "$GIT_TAG" != "$VERSION" ]; then
        tagopt+=(--tag "${REGISTRY}/${NAME}:${GIT_TAG}${PKG}")
    fi
fi

# The Oracle and Snowflake images require amd64.
docker buildx build --platform=linux/amd64 --pull \
  --label org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label org.opencontainers.image.authors='Sqitch Hackers <sqitch-hackers@googlegroups.com>' \
  --label org.opencontainers.image.url="https://hub.docker.com/r/sqitch/sqitch/" \
  --label org.opencontainers.image.documentation="https://github.com/sqitchers/docker-sqitch#readme" \
  --label org.opencontainers.image.source="https://github.com/sqitchers/docker-sqitch" \
  --label org.opencontainers.image.version="$VERSION" \
  --label org.opencontainers.image.revision="$(git rev-parse --abbrev-ref HEAD)" \
  --label org.opencontainers.image.vendor="The Sqitch Community" \
  --label org.opencontainers.image.licenses="MIT" \
  --label org.opencontainers.image.ref.name="sqitch${PKG}-${VERSION}" \
  --label org.opencontainers.image.title="Sqitch" \
  --label org.opencontainers.image.description="Sensible database change management" \
  "${tagopt[@]}" \
  --build-arg "VERSION=${VERSION}" \
  "$@" .
